### ISSUE TITLE
Update dinput8.dll to Open Sauce 2017

### ISSUE THREAD

**Issue by VoidsShadow** [yumiris/AmaiSosu#2]
SPV3 ships with modified 2017 dinput8.dll. However, AmaiSosu overwrites it with the 2015 Open Sauce 4.0 dinput8.dll.

**Comment by yumiris** [comment]
Eh, problem with the modified DLL is that there's no formality around it. Who made it? Where's the source code? How was it compiled?

**Comment by VoidsShadow** [comment]
Yeah... That's something I didn't think about.

**Comment by yumiris** [comment]
This exchange and closing of the issue sent me into absolute tears.
